version: '3.8'

services:
  scylla:
    image: scylladb/scylla:5.4
    container_name: scylla
    ports:
      - "9042:9042"       # CQL
      - "9160:9160"       # Thrift (có thể không cần)
      - "9180:9180"   # Prometheus metrics
    volumes:
      - scylla_data:/var/lib/scylla
    command: --smp 2 --memory 2G
    networks:
      - scylla_net

volumes:
  scylla_data:

networks:
  scylla_net:
    driver: bridge
