// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertEvent = `-- name: InsertEvent :execresult
INSERT INTO events (stream_id, payload) 
VALUES (?, ?)
`

type InsertEventParams struct {
	StreamID string
	Payload  json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertEvent, arg.StreamID, arg.Payload)
}
