// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Event struct {
	ID        int64
	StreamID  string
	Payload   json.RawMessage
	CreatedAt sql.NullTime
}
